name       : gtkhtml
version    : 4.10.0
release    : 2
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/gtkhtml/4.10/gtkhtml-4.10.0.tar.xz : ca3b6424fb2c7ac5d9cb8fdafb69318fa2e825c9cf6ed17d1e38d9b29e5606c3
license    : GPL-2.0
component  : desktop.library
summary    : GtkHTML is a lightweight HTML rendering/printing/editing engine.
description: |
    GtkHTML is a lightweight HTML rendering/printing/editing engine.
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(ORBit-2.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
